### ISSUE TITLE
Renaming artifact names on the download page

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#101]
Basically removing mention of 64bit and duplicate AppImage naming as they don't matter much anymore.

Windows:
`pcsx2-v1.7.2648-windows-64bit-AVX2.7z`
into
`pcsx2-v1.7.2648-windows-AVX2.7z` and when SSE4 is default and does flag check, later without the CPU instruction mention
and far future
`pcsx2-v1.7.2648-windows.7z`

Linux:
`pcsx2-v1.7.2648-linux-AppImage-64bit.AppImage`
into
`pcsx2-v1.7.2648-linux.AppImage`

**Comment by xTVaser** [comment]
This would be done at the API level / the actual names of the files, but its also kinda difficult (but not impossible) because in some previous releases these differences do matter (where there were a 32bit and a 64bit side by side).  

This means you have to have a whole bunch of conditional logic, for example, to assume 64-bit so you can still display it -- else we are then going to have another issue of people expecting it to work on their 32bit environment.

This is probably something worth looking into once the next stable is out, but ultimately the change will not happen in this repo.

**Comment by RedDevilus** [comment]
`pcsx2-v1.7.2648-linux-64bit.AppImage` Might be a good reduction atleast then.
