### ISSUE TITLE
Add RSS support for news posts

### ISSUE THREAD

**Issue by seapancake** [PCSX2/pcsx2-net-www#73]
User on the forum requested we support RSS on new site. Vaser can do although lower priority especially as we're still moving over the news articles.

Hugo documentation: https://gohugo.io/templates/rss/

**Comment by Binnette** [comment]
I will really appreciate to have RSS feed as well ❤️

**Comment by LinAGKar** [comment]
Now though, it uses relative URL:s for <link>s, which doesn't work properly. They need to be absolute. From what I can tell, this is because [baseURL](https://github.com/PCSX2/pcsx2-net-www/blob/656f75b827f201d4477a1a100e30ed31c91030f0/config.yaml#L4) is set incorrectly. It's just "/", but it should be "https://pcsx2.net/".

**Comment by Binnette** [comment]
> Now though, it uses relative URL:s for s, which doesn't work properly. They need to be absolute. From what I can tell, this is because [baseURL](https://github.com/PCSX2/pcsx2-net-www/blob/656f75b827f201d4477a1a100e30ed31c91030f0/config.yaml#L4) is set incorrectly. It's just "/", but it should be "https://pcsx2.net/".

Hi @LinAGKar, sorry I didn't understand your message. Is this a new bug?  If so, please consider opening a new issue. And please add details on how to reproduce your "bug". Have a nice day.

**Comment by LinAGKar** [comment]
Sorry, looks like the markdown formatter removed a bit of my message. The problem is that the `<link>`-tags in the RSS feed (https://pcsx2.net/index.xml) currently don't include the protocol and host parts ( `https://pcsx2.net`), they just start with `/`. I can open a new issue for that if you want.
