### ISSUE TITLE
Fallback download artifacts

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#86]
There is an issue with the latest Linux artifacts (GitHub fault)

![image](https://user-images.githubusercontent.com/24227051/161866010-889aa036-eaa0-4ced-9fb6-4cd3e001a219.png)

Perhaps a good idea to give an older artifact that is available as release?

It's uncommon to happen but a good idea in case something fails.

**Comment by xTVaser** [comment]
I think this current behaviour is acceptable.
1. it makes the issue highly visible so it is resolved
2. the previous release can be downloaded below from the table
3. we release at a rate lately where this is only an issue for a day or so

I also think its confusing (though technically valid) UX to mix versions on what is supposed to be the latest release section.

**Comment by seapancake** [comment]
I also agree that making it clear there was no release is the best option rather than being out of step between OS type (Although I was able to find a binary for 1.7.2570 and for every release in last 7 pages)

As long as we're greying out the Tux icon in the older binaries like we are doing for the latest release I think it's obvious enough and people will just skip back a build.

**Comment by refractionpcsx2** [comment]
That's fine, if that's the decision, but I can almost guarantee we will get questions like

1. Where is the latest linux version (because they won't look down)
or
2. Why have you stopped making the emulator linux compatible?

I would suggest at least having a note in the popup to say to get a previous release from the links below or something, just to hold peoples hands a bit.

**Comment by RedDevilus** [comment]
> That's fine, if that's the decision, but I can almost guarantee we will get questions like
> 
>     1. Where is the latest linux version (because they won't look down)
>        or
> 
>     2. Why have you stopped making the emulator linux compatible?
> 
> 
> I would suggest at least having a note in the popup to say to get a previous release from the links below or something, just to hold peoples hands a bit.

Yeah, I did it in the mind of a regular user, while I'm very sure everyone at the PCSX2 team will get what to do which is not something I would think of for a normal user and to be frank there are so many styles and things different compared to other emulators.

**Comment by seapancake** [comment]
I don't think we should design the site who lack the basic skills to look at the build list. We should target what is reasonable and not the lowest common denominator as you end up with a bunch of UI tweaks for lazy people that we then have to maintain and you also encourage people not to do the most basic of tasks. 

The other side of this argument is that accommodating for these kind of users is worth it due to the cost of our volunteers sanity in answering the same questions, if people are confident that this issue is so common that it's justified maybe it's worth doing.
