### ISSUE TITLE
Guides location (BIOS, etc)

### ISSUE THREAD

**Issue by RedDevilus** [PCSX2/pcsx2-net-www#89]
https://pcsx2.net/guides/ points to nowhere
https://pcsx2.net/guides/basic-setup/ points to the BIOS setup

In the future this could be expanded but it's not really exposed as easily to the user checking the site and not everyone uses or watches Discord.

**Comment by xTVaser** [comment]
This was intentional - to be able to make articles easily via markdown that aren't shown in the lists and can instead be linked directly to.
> it's not really exposed as easily to the user checking the site and not everyone uses or watches Discord.

It's exposed via the relevant sections on the downloads page 
![image](https://user-images.githubusercontent.com/13153231/162071910-32ca37bd-2e18-4d82-b9ef-480aecf39453.png)

**Comment by seapancake** [comment]
There is an argument we could add a menu link for 'Setup' or something like that. From a UX perspective it makes distinct sections download (Where to get) Compat list (What works) setup (How to make work). This would mean we could remove the current text from the downloads page.

Not something I'm super passionate about either way however it makes to me that it be split out and like Red says we could always expand it later on.
